### ISSUE TITLE
has someone gotten `k3s` to work?

### ISSUE THREAD

**Issue by bbortt** [testcontainers/testcontainers-rs-modules-community#200]
### Feature request description

I am trying to deploy a pod into `k3s`. I've followed the [contained test](https://github.com/testcontainers/testcontainers-rs-modules-community/blob/a7fd7d0408495c1b3364e3c01a50b7a22ac1a79c/src/k3s/mod.rs#L170) (roughly), but fail to get it working. I've also considered the [`pod_api.rs` example](https://github.com/kube-rs/kube/blob/main/examples/pod_api.rs) over at `kube-rs/kube`.

**has someone gotten this to work?** I always end up with: `Service(hyper_util::client::legacy::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })))`.

this happens to be thrown in the `pods.create` line:

```rust
pub(crate) async fn deploy_argocd(client: Client) {
    let pods: Api<Pod> = Api::default_namespaced(client.clone());

    let argocd_pod: Pod =
        parse_yaml("tests/resources/k3s/argocd.pod.yml").expect("Failed to read ArgoCD deployment");

    pods.create(&PostParams::default(), &argocd_pod)
        .await
        .expect("Failed to deploy ArgoCD to K3s");
}
```

### Image reference

[`k3s` feature](https://github.com/testcontainers/testcontainers-rs-modules-community/blob/a7fd7d0408495c1b3364e3c01a50b7a22ac1a79c/src/k3s/mod.rs)

**Comment by DDtKey** [comment]
Hi @bbortt 👋 
Could you say what version of `kube` do you use in your tests?

**Comment by bbortt** [comment]
@DDtKey thanks for the quick response. I saw that the test suite works and I can reproduce that. but it does only read pods, not create any new.. as soon as I go into this direction I end up with the mentioned error..

```toml
[dev-dependencies]
assert_cmd = "2.0.16"
k8s-openapi = { version = "0.22.0", features = ["latest"] }
kube = { version = "0.93.1", features = ["derive"] }
kube-derive = "0.93.1"
predicates = "3.1.2"
rustls = "0.23.12"
schemars = "0.8.21"
testcontainers-modules = { version = "0.9.0", features = [ "hashicorp_vault", "postgres"] }
```
